edition="2021"
enum_discrim_align_threshold=16
format_code_in_doc_comments=true
format_strings=true
hex_literal_case="Lower"
match_block_trailing_comma=true
imports_granularity="Crate"
normalize_comments=true
normalize_doc_attributes=true
overflow_delimited_expr=true
group_imports="StdExternalCrate"
struct_field_align_threshold=16
struct_lit_single_line=true
tab_spaces=2
use_field_init_shorthand=true
use_try_shorthand=true
where_single_line=true
wrap_comments=true
